# -*- coding: utf-8 -*-
"""iris_Data_Linear_reression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R5f_mRcl3v9sPSZG6hQm-LXgb7jcLiW
"""

# >> Problem statement : To predict PetalWidthCm

import pandas as pd
import numpy as np

# Splitting and model training
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Evaluation
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor  # pip install statsmodels

# visualisation libraries
import matplotlib.pyplot as plt  # important
import seaborn as sns

# To predict SepalLengthCm values by using various independent variables
# Id
# Dependent variable : SepalLengthCm
# Independent variables :
#     1. SepalWidthCm
#     2. PetalLengthCm
#     3. PetalWidthCm
#     4. Species

df = pd.read_csv('/content/IRIS.csv')
df.head()

df.shape

df.info()                             # There are no missing values

df['species'].value_counts()  # To convert into numeric values

df.columns

df['species'].value_counts().to_dict()

df['species'].replace({'Iris-setosa': 0, 'Iris-versicolor': 1, 'Iris-virginica': 2}, inplace = True)

df.head()

df.info()

# 1. Linearity

df.corr() # ## Linearity >> Correlation

sns.pairplot(df)
plt.show()

plt.figure(figsize = (10,8))                            # height*width
sns.heatmap(df.corr(), annot = True, cmap = 'YlGnBu')   # Annot means Values of corr, cmap is color
plt.show()

plt.figure(figsize = (8,8))
sns.heatmap(df.corr(), annot = True)
plt.show()
# plt.savefig('Correlation_Matrix.png')  # To save figure

# >> Between two independent variables:

# VIF (Variable Inflation Factors):
    # The VIF score of an independent variable represents how well the variable is explained by other independent variables.

    # VIF = 1 → No correlation
    # VIF = 1 to 5 → Moderate correlation
    # VIF >10 → High correlation

df1 = df.drop('sepal_length', axis = 1)
df1.head()

df1.to_numpy() # df1.values

vif_df = pd.DataFrame()
vif_df

vif_df["Features"] = df1.columns
vif_df

vif_list = []

for i in range(df1.shape[1]):  # no.of columns =  df1.shape[1]
    vif = variance_inflation_factor(df1.to_numpy(), i)
    vif_list.append(vif)

vif_list

vif_df['VIF'] = vif_list
vif_df

x = df.drop('sepal_length', axis =1)  # independent

y = df['sepal_length']                # dependent

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 3) # train_size = 0.8
x_train.head()

linear_reg_model = LinearRegression()  # class >> LinearRegression()
linear_reg_model

linear_reg_model.fit(x_train, y_train)

# Gradient descent algorithm
# best values of m and c

# y = m1x1 + m2x2 + m3x3 + m4x4 + c

linear_reg_model.coef_

linear_reg_model.intercept_

y_train_pred = linear_reg_model.predict(x_train)
y_train_pred[:5]   # predicted values

y_train[:5]  # actual

residual_train = y_train - y_train_pred
residual_train[:5]

mse = mean_squared_error(y_train, y_train_pred)
print('Mean squared error of training data', mse)

rmse = np.sqrt(mse)
print('Root Mean squared error of training data', rmse)

mae = mean_absolute_error(y_train, y_train_pred)
print( 'Mean absolute error of training data', mae)

r2_train_value = r2_score(y_train, y_train_pred)
print('R-aquared of training data', r2_value)

y_pred = linear_reg_model.predict(x_test)
y_pred[:5]   # predicted values

y_test[:5] # actual values

residual = y_test - y_pred
residual[:5]

mse = mean_squared_error(y_test, y_pred)
print('Mean squared error of testing data', mse)

rmse = np.sqrt(mse)
print('Root Mean squared error of testing data', rmse)

mae = mean_absolute_error(y_test, y_pred)
print( 'Mean absolute error of testing data', mae)

# r2_test_value = r2_score(y_test, y_pred)
# print('R-aquared of testing data', r2_value)

sns.scatterplot( x = y_train, y = residual_train)

df.head()

x_test[:5]



pred_test_3 = linear_reg_model.predict(test_3)
print('SepalLengthCm predicted value : ', pred_test_3[0])

sepal_width = 3.5
petal_length= 1.2
petal_width = 0.5
species = 2 # Irsi_virginica
# SepalLengthCm = ?

test_df = pd.DataFrame({'sepal_width' : [sepal_width], 'petal_length' : [petal_length],
                       'petal_width' : [petal_width], 'species' : [species] })
test_df

sepal_width = 3.5
petal_length= 1.2
petal_width = 0.5
species = 2 # Irsi_virginica
# SepalLengthCm = ?

pred_test_df = linear_reg_model.predict(test_df)
print('SepalLengthCm predicted value : ', pred_test_df[0])

def predict_sepallengthcm(	sepal_width,petal_length,petal_width,species):
    test_df = pd.DataFrame({'sepal_width' : [sepal_width], 'petal_length' : [petal_length],
                       'petal_width' : [petal_width], 'species' : [species] })
    pred_test_df = linear_reg_model.predict(test_df)
    sepal_length = np.around(pred_test_df[0], 2)
    print(f'Predicted SepalLength value is {sepal_length} cm')
    return sepal_length

predict_sepallengthcm(1,2,3,1)

predict_sepallengthcm(5.2,3.8,2.5,0)

x = x[:4]

x = x.dropna()
y = y.dropna()

linear_model = np.array([0.5999945, 0.76666667, 0.93333333, 1.1, 1.26666667])
import sklearn.linear_model
linear_model = sklearn.linear_model.LinearRegression()

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Define the x and y values
x = np.array([1, 2, 3, 4, 5])
y = np.array([1.9929336570674967, 2.9858673141349933, 3.97880097120249, 4.9717346282699867, 5.9646682853374833])

# Create a linear regression model
linear_model = LinearRegression()

# Fit the model to the data
linear_model.fit(x[:, np.newaxis], y)

# Calculate the slope and intercept of the linear regression line
slope = linear_model.coef_[0]
intercept = linear_model.intercept_

# Plot the scatter plot and the linear regression line
plt.scatter(x, y)
plt.plot(x, slope * x + intercept)
plt.xticks([1, 2, 3, 4, 5])
plt.show()

