# -*- coding: utf-8 -*-
"""Iris_Data_Linear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6sJDwDH7dtmEFtxUJBvGDFFadV1JPcO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from statsmodels.stats.outliers_influence import variance_inflation_factor

pip install sklearn.dataset

from sklearn.datasets import load_iris

# Data Gathering
iris_data = load_iris()
dir(iris_data)

print(iris_data.DESCR)

print(iris_data.data)
df = pd.DataFrame(iris_data.data)
df

df = pd.DataFrame(iris_data.data)
df

print(iris_data.feature_names)

print(iris_data.target)

# print(iris_data.data)
df = pd.DataFrame(iris_data.data)
df["Species"] = iris_data.target
df

df.describe()

df.info

df.boxplot()

# Feature Selection( Linearity, correlarity,Variance Inflation Factor)
# 1. Linearity
df.cov()       # covarience matrix

df.var()

#If there is strong correlaion btw independend variable and dependent variable then the result is strong
# 2. correlation
df.corr()

# 1.0  and -0.4 (High correlation)
# 0.4 (NO Correlation)

plt.figure(figsize= (7,5))
sns.heatmap(df.corr(),annot=True)
plt.savefig('Correlation.png')

correlation = df.corr().tail(1)

# 1.0  and -0.4 (High correlation)
# 0.4 (NO Correlation)

plt.figure(figsize= (15,2))
sns.heatmap(correlation,annot=True)
plt.savefig('Correlation.png')

# No Multicolinerity

3.# VIF >> Variance Inflation Factor

# 1 to inf
# 1 to 5 best
# 5 to 10 moderate

df.columns

df.shape[1]

for i in range(df.shape[1] -1):
  print(i)

for i in range (df.shape[1],-1):
  print(i)
  vif = variance_inflation_factor(df,to_numpy(),i)
  print("VIF:",vif)

x = df.drop ('Species', axis=1)
x.columns

for i in range (df.shape[1],-1):
  print(i)
  vif = variance_inflation_factor(df,to_numpy(),i)
  print(f"{df.columns[i]}",vif)

vif_list = []
for i in range(df.shape[1] - 1, -1, -1):
    vif = variance_inflation_factor(df.to_numpy(), i)
    vif_list.append(vif)

s1 = pd.Series(vif_list, index= df.columns)  # Use df.columns instead of x.columns
s1.sort_values().plot(kind = 'bar')

# Model Training
# Train Test Split

x = df.drop('Species',axis=1) #2D
y = df['Species'] #1D
x_train, y_train, x_test, y_test = train_test_split(x,y,test_size=0.2,random_state=0,shuffle=True)
x_train

y_train

x_test

print("Length of x_train:", len(x_train))
print("Length of y_train:", len(y_train))

pip install LinearRegression

from sklearn.linear_model import LinearRegression

x_train = x_train[:30]
y_train = y_train[:30]

linear_reg = LinearRegression()
linear_reg.fit(x_train, y_train)

linear_reg.coef_

linear_reg.intercept_

linear_reg.predict

linear_reg.coef_ = linear_reg.coef_.reshape(-1, 1)

import numpy

x_test = numpy.array(x_test)
x_test = x_test.reshape((120, 1, 1))
linear_reg.coef_ = linear_reg.coef_[0]
linear_reg.coef_ = linear_reg.coef_.reshape((1, 1))

x_test = x_test.reshape((120, 1, 1))
linear_reg.coef_ = linear_reg.coef_[0]
linear_reg.coef_ = linear_reg.coef_.reshape((1, 1))

x_test = x_test.reshape(-1, 1)

x_test = x_test.reshape(-1, 4)
linear_reg = LinearRegression()
linear_reg.fit(x_train, y_train)

# Evaluation
y_pred = linear_reg.predict(x_test)
print(y_pred)

y_pred[:10]

y_test[:10]

y_true = np.array([[1, 2, 3], [4, 5, 6]])
y_pred = np.array([[0.5, 0.7, 0.9], [0.3, 0.6, 0.8]])

y_true = y_true.reshape((y_true.shape[0], y_pred.shape[1]))

y_pred = np.array([[0.5, 0.7, 0.9], [0.3, 0.6, 0.8]])

y_true = locals()['y_true']
y_true = y_true.reshape((y_true.shape[0], y_pred.shape[1]))

if y_pred.shape != (30, 1):
  y_pred = y_pred.reshape(-1, 1)

y_pred = y_pred[:30]
y_pred = np.zeros((30, 1))
y_pred[:6] = y_pred[:6]

y_pred = y_pred.reshape(30, 1)

# Evaluation of testing Data


import numpy as np
from sklearn.metrics import mean_squared_error

y_test_np = np.array(y_test)
y_pred = y_pred.reshape(-1, 1)

mse = mean_squared_error(y_test_np, y_pred)
print("Mean Squared Error:", mse)

rmse = np.sqrt(mse)
print("Root mean squared  Error:", rmse)

mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error: ", mae)

r_squared = r2_score(y_test, y_pred)
print("R Squared value is:", r_squared )

# Evaluation of training Data

y_pred_train = linear_reg.predict(x_train)

mse = mean_squared_error(y_train, y_pred_train)
print("Mean Squared Error:", mse)

rmse = np.sqrt(mse)
print("Root mean squared  Error:", rmse)

mae = mean_absolute_error(y_train, y_pred_train)
print("Mean Absolute Error: ", mae)

r_squared = r2_score(y_train, y_pred_train)
print("R Squared value is:", r_squared )

row_10 = x_train.iloc[10]
row_10

y_pred_new = linear_reg.predict([row_10])
y_pred_new

# R squared value for all variable
x_train.columns

x_train = x_train[:30]
y_train = np.concatenate((y_train, y_train), axis=0)

x_train.shape
if not x_train.shape[0]:
  raise ValueError("x_train is empty.")
  inear_reg.fit(x_train, y_train)

linear_reg = LinearRegression()
if i > 0:
    linear_reg.fit(x_train[:i], y_train[:i], sample_weight=np.ones(i))

x_train = x_train.sample(n=100, replace=True)

linear_reg = LinearRegression()
if i > 0:
    linear_reg.fit(x_train[:i], y_train[:i], sample_weight=np.ones(i))

linear_reg = LinearRegression()
linear_reg.fit(x_train[:i], y_train[:i])

linear_reg = LinearRegression()
linear_reg.fit(x_train[:i], y_train[:i], sample_weight=np.ones(i))

r_squared_values_list = []
for i in range(1, x_train.shape[1]+1):
  print(i)
  linear_reg = LinearRegression()
  linear_reg.fit(x_train[:i], y_train[:i])
  r_squared = r2_score(y_test, y_pred)
  r_squared_values_list.append(r_squared)
  # print(" R Squared value is : ", r_squared)
r_squared_values_list

linear_reg.fit(x_train[:i], y_train[:i])

def get_r2_values(x_train, y_train):
  """
  This function calculates the R-squared and adjusted R-squared values for each feature in the training data.

  Args:
    x_train: The training data.
    y_train: The training labels.

  Returns:
    A DataFrame with the R-squared and adjusted R-squared values for each feature.
  """

  r_squared_values_list = []
  adj_r2_list = []
  for feature in x_train.columns:
    model = LinearRegression()
    model.fit(x_train[[feature]], y_train)
    r_squared_values_list.append(model.score(x_train[[feature]], y_train))
    adj_r2_list.append(model.score(x_train[[feature]], y_train, sample_weight=x_train.shape[0]))

  if not r_squared_values_list:
    return pd.DataFrame()

  r2_df = pd.DataFrame({"R2 Values": r_squared_values_list,"Adj R2": adj_r2_list},index =x_train.columns)
  return r2_df

correlation.T

# 1.Linearity
# 2. No Multicolinearity
# 3. Normality of Residual
# 4. Homoscedasticity(Residual)

# Residual = (Ya - Yp)

# Normality Of Residuals

# Residual values should be normally distributed

# Residual = (Ya - Yp)
# Residual Can be positive or negative or zero

# How to check Normality:
#       1.Visualization Library/Tool(Mataplotlib or Seaborn):
#             1.kdeplot
#             2.histplot

#       2. Hypothesis Testing:
#           1. shapiro
#           2. kstest
#           3. normaltest

#       3. QQPlot (Powerful method to verify normality)

#       4. Skewness of Residuals

y_train

y_pred_train

y_train[:5]

y_pred_train[0:5]

# Residuals
y_train[:5] - y_pred_train[0:5]

y_pred_train = y_pred_train.reshape((120, -1))

y_train - y_pred_train

mse = (((y_train - y_pred_train)**2).sum())/ 404
mse

mae = ((np.abs(y_train - y_pred_train)).sum())/404
mae

residual = np.random.randn(100)
sns.kdeplot(residual, fill=True)

sns.histplot(residual)

sns.histplot(residual,kde=True)

sns.histplot(df['Species'],kde=True)

array = np.random.randn(1000)
sns.histplot(array, kde=True)

import statsmodels.api as sm

sm.qqplot(residual,line='45',fit=True)

sm.qqplot(df['Species'],line='45',fit=True)

sm.qqplot(array,line='45',fit=True)

# Skewness

# Positive Skewness  >>  Tail of the Distribution is longer towards right hand side
# Negative Skewness  >>   Tail of the Distribution is longer towards right hand side
# Symmetrical Data   >>   Bell Shape curve

# -0.5 to +0.5  >> Symmetrical Distribution(0.05,-0.05,-0.3,0,0.08,0.3,0.4)
# -1 to -0.5    >> Negatively Skewed Data (-0.6,-0.8,-0.9)
# 0.5 to 1.0    >> Positively Skewed Data (0.6,0.8,0.9)

# Skew > 1.0 : Highly Positively Skewed Data(1.45, 1.8)
# skew < -1.0 :  Highly Negatively Skewed Data (-1.8,-2.4)

sns.kdeplot(residual)

mean = df['Species'].mean()
print("Mean:", mean)

median = df['Species'].median()
print("Median:", median)

mode = df['Species'].mode()
print("Mode:", mode)

# mean > mode > median  : Positively skewed Data
# mean < mode < median  : Negatively skewed Data

import pandas as pd
s1 = pd.Series(residual)
s1

mean = s1.mean()
print("Mean:", mean)

median = s1.median()
print("Median:", median)

mode = s1.mode()
print("Mode:", mode)

