# -*- coding: utf-8 -*-
"""Linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1olwF4NBnTblRmd3wDUV350W9_S2ogNsG
"""

import tensorflow as tf
import numpy as np

x=np.array([2800,3000,3200,3600,4000])
y=np.array([550000,565000,610000,680000,725000])

x

y

model=tf.keras.models.Sequential()

model.add(tf.keras.layers.Dense(1,input_shape=(1,)))

model.compile(optimizer='sgd',loss=tf.keras.losses.mean_absolute_error)

model.fit(x,y,epochs=100)

model.predict(x=[2000])

model.predict(x=[2500])

