# -*- coding: utf-8 -*-
"""Linear_Regression_AutoData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JhRncqYb861OjvFjyMNgl7iz4lBQ8gCb
"""

import pandas as pd
import numpy as np

from sklearn.datasets import load_diabetes
from statsmodels.stats.outliers_influence import variance_inflation_factor

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import matplotlib.pyplot as plt
import seaborn as sns

# Problem Statement

# To predict the car price using various variables


# Dependent Variable: Price

# Independent Variables:

#         ['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
#        'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
#        'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
#        'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
#        'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
#        'highway-mpg']

# Data reading and Gathering

df = pd.read_csv("/content/autos_dataset.csv")
df

df.head().T

df.columns

df.info()

# Exploratory Data Analysis

df.isna().sum()

df

df.replace({"?":np.nan},inplace=True)

df.isna().sum()

df.isna().mean()*100

# symboling

df["symboling"].value_counts()

# Normalized-losses

df['normalized-losses'].head(30)

# mean >> If outliers are not present
# median >> If Outliers are present
# KNN Imputer >> Small Dataset with more than 10-15 %

df.describe()

df['normalized-losses'] = df['normalized-losses'].astype(float)

df['normalized-losses'].mean()

df['normalized-losses'].median()

df['normalized-losses'].fillna(df['normalized-losses'].median())

df.info()

# make

df['make']

df['make'].value_counts()

# fuel-type

df['fuel-type']

df['fuel-type'].value_counts()

df['fuel-type'].replace({"gas":0,"diesel":1},inplace=True)

df['fuel-type']

# aspiration

df['aspiration'].value_counts()

df['aspiration'].replace({"std":0,"turbo":1},inplace=True)

df['aspiration']

# num-of-doors

df['num-of-doors'].value_counts()

df['num-of-doors'].value_counts().to_dict()

df['num-of-doors'].replace({"four":4,"two":2},inplace=True)

df['num-of-doors'].fillna(df['num-of-doors'].mode()[0],inplace= True)

df['num-of-doors'] = df['num-of-doors'].astype(int)
df['num-of-doors']

# body-style

df['body-style'].value_counts()

df = pd.get_dummies(df,columns=['body-style'])
df

# drive-wheels

df['drive-wheels'].value_counts()

df['drive-wheels'].value_counts().to_dict()

df['drive-wheels'].replace({'fwd': 1, 'rwd': 0, '4wd': 2},inplace = True)

df['drive-wheels']

# engine-location

df['engine-location'].value_counts()

df['engine-location'].replace({"front":1,"rear":0},inplace=True)

df['engine-location']

# wheel-base

df['wheel-base']

df.info()

# engine-type

df['engine-type'].value_counts()

df = pd.get_dummies(df,columns=['engine-type']) # one hot encoding for engine-type columns
df

# num-of-cylinders

df['num-of-cylinders']

df['num-of-cylinders'].value_counts()

df['num-of-cylinders'].value_counts().to_dict()

df['num-of-cylinders'].replace({'four': 4,   # label encoading
 'six': 6,
 'five': 5,
 'eight': 8,
 'two': 2,
 'twelve': 12,
 'three': 3})

df['num-of-cylinders']

df.info()

